[package]
name = "forensic-file-search"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
sha1 = "0.10.6"
sha2 = "0.10.9"
hex-literal = "1.0.0"